In [1]:
#Simple Linear Regression - SLR will use clusters of 
#one dependent variable and one independent variables to make predictions

In [2]:
# in an equation y=B0 +B1X  B0 is the intercept and B1 is the slope

In [3]:
# Prediction of dependent variable and finding the perfect fit of the regression line is key for SLR 

In [4]:
# Regresion is functionally done by putting all independednt variables in one NumPy array 
# and the dependent variables in another NumPy Array

In [5]:
# uncertainty is taken into account by assuming a small random value is added 
# to the point on the line; this is called noise. 

In [6]:
#We will require scikit-learn library to do regresssion

In [7]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
df=pd.read_excel("C:\\Users\\ARNOB\\Desktop\\pricebinning.xlsx")

In [8]:
from sklearn.linear_model import LinearRegression #Import Linear Regression Model from Scikit-Learn
lm=LinearRegression() #Creating a empty Linear Regression objectusing the constructor
df=df.dropna()#It is essential to deal with any EmptyCells before trying regression.
#We can use the fill options with mean or something else

In [9]:
#We define the dependent and indpendent variable
x=df[['highway mpg']]
y=df[['price']]
# then we uselm.fit(x,y) to fit the model, i.e. find the parameters B0=intercept and B1=slope
lm.fit(x,y)
#We can obtain a prediction

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
Yhat=lm.predict(x)

In [11]:
lm.intercept_ #we can see the intercept, B0

array([32468.309406])

In [12]:
lm.coef_ #we can see the slope,B1

array([[-655.28135573]])

In [13]:
# Multilinear Regression So EASY in PYTHON 

In [14]:
z=df[['horsepower','curb weight','engine size','highway mpg']] # We will use 4 independent variables
#Then we train the model like before
lm.fit(z,df['price'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
#We can also make a prediction again
Yhat=lm.predict(z)

In [16]:
#We find the intercept again
lm.intercept_

-15469.047120325764

In [17]:
#Find the coefficients
lm.coef_

array([20.35983585,  8.25411089, 33.01845058, 22.20517885])

In [18]:
#So y=20.35983585*horsepower+8.25411089*curb weight+33.01845058*engine size+22.20517885*highway mpg-15469.047120325764